### PR TITLE
Wip/carter/forward port 0.12.1 tests into master

### PR DESCRIPTION
**Pull request by cartazio**
@Shimuuar  @lehins  heres a hopefully simpler forward port that should be largely the same as 
https://github.com/haskell/vector/pull/302, but which keeps the semigroup trick for describing the associativities of the maxBy and MinBy

### CODE REVIEW

**Comment by cartazio** [comment]
derp, property test fail :)

**Comment by cartazio** [comment]
oh, found the issue (relates to the stronger property test that doesn't work well for Float/Double with the current QC generators for the same types)

**Comment by cartazio** [comment]
https://github.com/nick8325/quickcheck/issues/295  --- i'm commenting out one test in QC test for now, though we could copy the fix by @phadej intree perhaps if needed , im open to either approach

**Comment by cartazio** [comment]
@lehins @Shimuuar i'm sure you two have some good change requests for this, i look forward to the feedback :) 

many thanks

**Comment by cartazio** [comment]
at the end this should all get squashed, i'm a bit derpy and making 1-2 flubs in cleaning this up locally

**Comment by cartazio** [comment]
theres 1-2 things to still cleanup once i get the tests green, like cleaning up how i fixed changing the TestTree type aliases in the modules, but should be good overall I hope :)

**Comment by lehins** [comment]
@cartazio I appreciate you trying to help with this, but this is no way to port back/forward existing changes. This looks like a totally separate PR. The way @Shimuuar did it in #302 is the right way.
If there are some changes you'd like to add on top of the changes ported forward, feel free to submit a PR just with those changes. Make sure not to create any branches on this repo.

**Comment by cartazio** [comment]
I guess I understand. I hope we can learn to work together in a positive
way in the future. And again I’m sorry that I’ve been frustrating to
collaovrate with in the past

The semigroup test is there to validate that the semantics of maxby In
vector vs base have the desired meaning with some clarity on the left vs
right tie breaking.

I’ve asked a friend who you may be more comfortable with to see about
preparing that itch

**Pull request closed without merging**
