### PR TITLE
Fix issues with vector slice function

### LINKED ISSUE #257: Segfaults and "internal errors" when vector slice overflows
I reported this for GHC first. See <https://gitlab.haskell.org/ghc/ghc/issues/17233> for full details (could be copied here if clearly a bug in vector). May be related to #188?

### PR DESCRIPTION
**Pull request by lehins**
Fixes #257

### CODE REVIEW

**Comment by cartazio** [comment]
wonderful! of course we need to fix that fusion rule, but this is better than not. 

(i think we could maybe change the rules around to push around the interval information into the fused code, but thats not what we 're here for today)

**Comment by lehins** [comment]
To be honest I am pretty sure it is possible fixing that fusion rule without changing semantics of `slice` not throwing an error.

**Comment by cartazio** [comment]
it is possible or *impossible*? i'm confused :)

**Comment by lehins** [comment]
Sorry, not possible :man_facepalming:

**Comment by cartazio** [comment]
i'm going to say "yes, impossible if we dont change the rules/fusion stuff", but i THINK if we add some hooks for "evidence" passing that we can later erase, there might be a way :)

**Comment by cartazio** [comment]
this may be slightly beyond what GHC can currently do, and that might motivate some fun slow motion compiler hacking

**Comment by lehins** [comment]
I've been wrong before ;) There might be a trick that I am simply not aware of.

**Pull request merged**
