### PR TITLE
Allow building with semigroups-0.19

### PR DESCRIPTION
**Pull request by RyanGlScott**
This will also require a revision on the current Hackage release of `vector`.

### CODE REVIEW

**Comment by cartazio** [comment]
lets do it!

**Comment by RyanGlScott** [comment]
@cartazio, can you take care of the corresponding Hackage revision?

**Comment by cartazio** [comment]
sure thing!
which versions shall i relax? just current tip?

**Comment by cartazio** [comment]
http://hackage.haskell.org/package/vector-0.12.0.3 look good now?

**Comment by RyanGlScott** [comment]
Indeed, I think just revising 0.12.0.3 will suffice. Thanks!

**Pull request merged**
