### PR TITLE
Add since pragmas to haddock

### LINKED ISSUE #169: add a since 0.11 to basic initialize?
probably some other related ones. @dolio @hvr  @RyanGlScott  any others come to mind? :)

### PR DESCRIPTION
**Pull request by cartazio**
Fixes #169, also added pragmas to functions/instances defined in
0.12.1. Could've missed some

### CODE REVIEW

**Comment by cartazio** [comment]
@Shimuuar figured we should cherrypick that onto 0.12.1.2 as well
cc @lehins @RyanGlScott @chessai

**Comment by cartazio** [comment]
@lehins @Shimuuar sdist + tag this as 0.12.1.2?

**Comment by cartazio** [comment]
(or are there other things i'm forgetting)

**Comment by lehins** [comment]
@cartazio I think we are good to make that `0.12.1.2` release, don't forget to deprecate the other two `0.12.1.x` versions.

**Comment by Shimuuar** [comment]
Wait until CI finishes? (: Can't think about anythink else

**Comment by lehins** [comment]
Yeah, CI goes without saying :)

**Comment by cartazio** [comment]
:))))

**Pull request merged**
