### PR TITLE
Add since pragmas to haddock

### LINKED ISSUE #169: add a since 0.11 to basic initialize?
probably some other related ones. @dolio @hvr  @RyanGlScott  any others come to mind? :)

### PR DESCRIPTION
**Pull request by Shimuuar**
Fixes #169, also added pragmas to functions/instances defined in
0.12.1. Could've missed some

### CODE REVIEW

**Comment by cartazio** [comment]
probably should include for cherrypick onto 0.12.1.2?

**Comment by Shimuuar** [comment]
Yes. That's good idea. It only touches haddocks

**Comment by Shimuuar** [comment]
This PR is part of 0.12.1 already so I'm merging it into master

**Comment by cartazio** [comment]
Thx :)

**Comment by cartazio** [comment]
Eep, i personally prefer we not add the extra merge request commits and instead make sure the squash commit includes the original commit and a reference to the merge/pull request number.  Aka stuff should fr apply clean and just have the extra provenance data included in the commit.  It’s fine.  But I hope that makes sense ?

**Pull request merged**
