### PR TITLE
Add some doctests

### PR DESCRIPTION
**Pull request by Shimuuar**
They're mostly copied from #101 with exception of maximum/minimum related ones (see #362, they're to be fixed separately). Also examples from accum & accumulate are converted to doctests

### CODE REVIEW

**Comment by lehins** [comment]
Taking a quick peek at it looks great. One comment I have right now is that it is important to stay consistent with respect to doctests because users will mimic them in their code. In this case in particular I am talking about qualified imports. I've personally almost always used these:

```haskell
import qualified Data.Vector as V
import qualified Data.Vector.Mutable as MV
import qualified Data.Vector.Generic as VG
import qualified Data.Vector.Generic.Mutable as MVG
import qualified Data.Vector.Storable as VS
import qualified Data.Vector.Storable.Mutable as MVS
import qualified Data.Vector.Primitive as VP
import qualified Data.Vector.Primitive.Mutable as MVP
import qualified Data.Vector.Unboxed as VU
import qualified Data.Vector.Unboxed.Mutable as MVU
```

Those were also the names I've used in recently added PR #360 

I am not terribly set on those names, but keeping them consistent I think is very important. However I really don't like  the  `as S`  for storable vector, because often `import qualified Foreign.Storable as S` also shows up in scope,

**Comment by Shimuuar** [comment]
I always used G/V/P/U for qualified imports. But VG/V/VP/VU is just as good to me. I'll update doctests

**Comment by lehins** [comment]
@Shimuuar If you are busy I can update those qualified imports. I'd, like to merge this PR, just so I can included these doctests in the `vector-0.12.2.0` release I'd like to cut today

**Comment by Shimuuar** [comment]
@lehins Done.

**Comment by lehins** [comment]
@Shimuuar Nice, thank you. I'll  merge it when CI completes

**Review by Bodigrim — APPROVED** [review]

**Pull request merged**
