### PR TITLE
Add monadic variants for iterateN, unfoldr, unfoldrN

### PR DESCRIPTION
**Pull request by Shimuuar**
I needed such functions while working on some toy Monte-Carlo simulations. It turned out that all required stream fusion machniery for these functions was present already but they weren't implemented for some reason

There're no tests. I don't really know what to test here.

### CODE REVIEW

**Comment by Daniel-Diaz** [comment]
Bump. I'm interested in this too!

**Comment by cartazio** [comment]
this is a nice PR, we're catching up on stuff, but will look at it in the next week or so. if you find some time to clean it it up for master please let me know, else happy to have a go myself :)

**Comment by Shimuuar** [comment]
Will do that

**Comment by cartazio** [comment]
yay :) 
i may want some help de bit rotting the benchmark suite once @dolio finishes moving to the new style CI setup, at which point we could add this stuff to the benchmark suite.

@Shimuuar hope you dont mind that side diversion :0

**Comment by Shimuuar** [comment]
I've rebased branch to the current master.

**Comment by cartazio** [comment]
Thanks! We'll review it soon! Awesome

**Comment by fhaust** [comment]
As this was apparently merged into master, has this ever been released?

**Comment by glguy** [comment]
No, you you look at http://hackage.haskell.org/package/vector you'll see the upload date is earlier than the merge.

**Pull request merged**
