### PR TITLE
Implement (<$) for Vector

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Out of curiosity, is there actually a noticeable performance improvement with this change?

**Comment by chessai** [comment]
I'm also interested in benchmarks for this.

**Comment by RyanGlScott** [comment]
Moreover, this PR doesn't seem to build, as [observed on Travis](https://travis-ci.org/haskell/vector/jobs/538791118#L647):

```
[ 7 of 21] Compiling Data.Vector.Fusion.Bundle.Monadic ( Data/Vector/Fusion/Bundle/Monadic.hs, /home/travis/build/haskell/vector/dist-newstyle/build/x86_64-linux/ghc-8.6.4/vector-0.12.0.1/build/Data/Vector/Fusion/Bundle/Monadic.o )
Data/Vector/Fusion/Bundle/Monadic.hs:288:40: error:
    • Couldn't match expected type ‘Int’ with actual type ‘Size’
    • In the first argument of ‘replicate’, namely ‘n’
      In the expression: replicate n a
      In an equation for ‘<$’: (<$) a Bundle {sSize = n} = replicate n a
    |
288 |   (<$) a Bundle{sSize = n} = replicate n a
    |                                        ^
```

**Comment by sjakobi** [comment]
Sorry for never following up with benchmarks! I'm not very interested in this anymore, and I wouldn't mind if the PR is closed.

**Comment by cartazio** [comment]
I’ll review / experiment with this none the less when I do a sweep of
vector work over the holiday season :)

**Comment by lehins** [comment]
To be honest, I don't think suggested implementation of `<$` in this PR is even a good idea, because it will force the size of a stream if it is not known, which means it is not good for fusion. Here is an example.

```haskell
  let v = V.unfoldr (\x -> if x == 1000000 then Nothing else Just (x, x + 1)) 0
  print $ V.take 4 (1 <$ v)
```

When compiled with optimizations currently it will only evaluate first 4 elements of `v`, where `length` in `(<$) v = replicate (length v) a`, will cause evaluation of the full 1000000 of elements.

Voting to close this PR.

**Comment by lehins** [comment]
Spoke a bit too soon, fusion doesn't work that reliably, so current implementation might also force the full vector in above example.

This will diverge:
```haskell
  let v = V.unfoldr (\x -> Just (x, x + 1)) 0
  print $ V.take 4 (1 <$ v) -- diverges
```

While this will print `[1,1,1,1]`:
```
main = do
  let v = V.unfoldr (\x -> Just (x, x + 1)) 0
  print $ V.take 4 (1 <<$ v) -- prints [1,1,1,1]

(<<$) = V.map . const
{-# INLINE (<<$) #-}
```

So, maybe giving a `Functor` custom implementation for `<$` is a good idea, but just not the one that forces the full length. What y'all think?

**Comment by sjakobi** [comment]
Here's just another random idea that might work better with fusion:

```diff
--- a/Data/Vector/Fusion/Bundle/Monadic.hs
+++ b/Data/Vector/Fusion/Bundle/Monadic.hs
@@ -284,6 +284,11 @@ instance Monad m => Functor (Bundle m v) where
   {-# INLINE fmap #-}
   fmap = map
 
+  {-# INLINE (<$) #-}
+  (<$) a b@Bundle{ sSize = n } = case n of
+      Exact n' -> replicate n' a
+      _        -> map (const a) b
+
 -- | Map a function over a 'Bundle'
 map :: Monad m => (a -> b) -> Bundle m v a -> Bundle m v b
 {-# INLINE map #-}
```

**Comment by lehins** [comment]
@sjakobi Yeah, that looks very promising! Do you wanna replace the current implementation with your newly suggested approach? We can then test it out and see how it works out with regards to performance and fusion

**Comment by lehins** [comment]
Superseded by #323

**Pull request closed without merging**
