### PR TITLE
GHC 9.4 Support

### PR DESCRIPTION
**Pull request by parsonsmatt**
Pending on https://github.com/haskell/primitive/pull/340

Tests fail to build for a problem with `inspection-testing`. PR: https://github.com/nomeata/inspection-testing/pull/65

With that PR, tests pass, except for `doctest`, which has [has a bunch of build errors](https://github.com/sol/doctest/pull/375).

### CODE REVIEW

**Comment by Bodigrim** [comment]
I revised the released version of `vector` to allow GHC 9.4: https://hackage.haskell.org/package/vector-0.12.3.1/revisions/

**Comment by Bodigrim** [comment]
I revised the released version of `vector` to allow GHC 9.4: https://hackage.haskell.org/package/vector-0.12.3.1/revisions/

**Comment by phadej** [comment]
@Bodigrim who about `vector-0.13` ?

**Comment by Bodigrim** [comment]
@phadej done.

**Comment by phadej** [comment]
@Bodigrim thanks!

**Comment by lehins** [comment]
I think we can close this issue since bounds were fixed in #445

**Pull request closed without merging**
