### PR TITLE
Implement partitionWith

### PR DESCRIPTION
**Pull request by andrewthad**

### CODE REVIEW

**Comment by andrewthad** [comment]
Resolves https://github.com/haskell/vector/issues/154. Still needs tests and exports from `Unboxed` and `Storable`.

**Comment by andrewthad** [comment]
This feature is now complete and has been added to the test suite. The name `partitionWith` is up for bikeshedding if a maintainer would prefer something else.

**Comment by RyanGlScott** [comment]
@cartazio, there is the [`vector-benchmarks` package](https://github.com/haskell/vector/blob/5b6e8d496f192be69eed625dfde1b3221c565328/benchmarks/Main.hs) living in the `benchmarks` directory, but it's far from comprehensive at the moment.

**Comment by dolio** [comment]
Looks good to me.

**Pull request merged**
