### PR TITLE
Make it build with ghc 8.2

### PR DESCRIPTION
**Pull request by erikd**
Requires patched [test-framework](https://github.com/erikd/test-framework).

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Thanks. However, I'm reluctant to merge this at the moment, since the `-O2` test suite fails to build on Travis due to an [out-of-memory error](https://travis-ci.org/haskell/vector/jobs/218749281#L1270). On my local machine with 16 GB of memory, I can at least build that test suite (after waiting quite a while), but then the test suite appears to run forever.

**Comment by RyanGlScott** [comment]
I've filed a corresponding GHC issue here: [Trac #13535](https://ghc.haskell.org/trac/ghc/ticket/13535)

**Comment by cartazio** [comment]
Is this because of the bundle rather than stream rep or because of the
weird way the vector test suite is written. Or because of fusio. Blowup ?


Happy to hear O2 is tickling some issues

**Comment by phadej** [comment]
Without this testing GHC-8.2.1-rc1 is rather difficult

**Comment by dolio** [comment]
Ran tests locally (only took 20GB of memory to compile). They passed. So I'm merging and bumping the dependencies on hackage.

**Pull request merged**
