### PR TITLE
Add examples for some functions in Data.Vector

### PR DESCRIPTION
**Pull request by MaxGabriel**
Here's an image of what the generated Haddocks look like:
image

I'm not sure if you have strong preferences on how exactly to format the code examples; I can be flexible with that.

### CODE REVIEW

**Comment by MaxGabriel** [comment]
It looks like the `git clone` failed for the [GHC=head build](https://travis-ci.org/haskell/vector/jobs/88704511):

```
75.13s$ git clone --depth=50 https://github.com/haskell/vector.git haskell/vector
Cloning into 'haskell/vector'...
fatal: unable to access 'https://github.com/haskell/vector.git/': Couldn't resolve host 'github.com'
The command "eval git clone --depth=50 https://github.com/haskell/vector.git haskell/vector" failed. Retrying, 2 of 3.
```

That may need to be retried.

**Comment by cartazio** [comment]
this is a cool idea, @dolio  and i are doing some cleanup on master at the moment, but having doc tests style examples that are also part of our tests would be pretty sweet, pardon the slow turn around on this. would that be something you'd be interested in helping drive?

**Comment by MaxGabriel** [comment]
I haven't been working on Haskell stuff for awhile, so realistically, probably not :(

**Comment by Bodigrim** [comment]
This looks like a first step for #296, doesn't it?

**Comment by Bodigrim** [comment]
This is not an acceptable format for `doctest`, is it?

**Comment by 5outh** [comment]
Can this be merged? Even if it's not doctest-compatible it's a step in the right direction of adding good examples.

**Comment by Bodigrim** [comment]
We run doctests on CI, so this is pretty much a deal breaker. But a similar in scope PR with passing doctests (which is not hard at all) could be very well accepted.

**Comment by Shimuuar** [comment]
Superceded by #363 and #364

**Pull request closed without merging**
